import React from 'react';

import Footer from '../Componenets/Footer';
const Home1 = () => {
  return (
    <div>
     
      <div className='flex flex-row items-center justify-center text-6xl font-extrabold font-Calibri py-6'>
        <h1>Welcome to our website</h1>
        
      </div>
     
        <div className='font-bold flex flex-row items-center justify-center text-3xl'> 
        <h2>LifeNest – Simplify, Organize, Thrive</h2>
        </div>
        <div className='font-semibold text-1xl text-2xl leading-relaxed flex flex-col items-start justify-start px-10 py-6'> 
        <p>LifeNest is your all-in-one digital productivity hub, thoughtfully crafted to help you take control of your daily life and bring structure to your routines. Whether you're capturing spontaneous thoughts, maintaining a consistent habit, organizing your daily schedule, or securely managing essential contacts, LifeNest brings all these features together in one seamless platform.</p>
       
        </div>
        <div className='font-semibold text-1xl text-2xl leading-relaxed flex flex-col items-center justify-center px-10 py-4'> 
       <p>From students and professionals to anyone seeking a more intentional and organized lifestyle, LifeNest offers the tools you need to stay focused, boost productivity, and reduce mental clutter. With its intuitive interface and user-friendly design, it transforms everyday tasks into manageable, meaningful actions — empowering you to simplify your life and thrive with confidence.

</p>

       
        </div>
        <div className='font-bold text-1xl text-2xl leading-relaxed flex flex-col items-start justify-start px-10 py-4'> 
       <p>Key Features:</p>

       
        </div>
        <div className='font-semibold text-1xl text-2xl leading-relaxed flex flex-col items-start justify-start px-10'> 
       <ul>
        <li>📝 Note-Taking: Capture thoughts, ideas, and to-dos with a clean, user-friendly interface.</li>
        <li>📈 Habit Tracker: Build and track habits that lead to lasting personal growth.</li>
        <li>🗓️ Daily Planner: Organize your schedule, set goals, and stay on top of your day.</li>
        <li>📱 Phone Number Manager: Safely store, categorize, and access your important contacts anytime.</li>
       </ul>

       
        </div>
        <p>Note: This company doesn't exist in real life its just a prototype sample for project.</p><br />
        <p>Name and logo is generated by AI</p>
        <div className='py-4'>
          <Footer/>
        </div>


    </div>
  )
}

export default Home1
